apiVersion: v1
kind: Pod
metadata:
  name: saleor
  labels:
    app: marketplace
spec:
  containers:
    - name: database
      image: postgres:11.6-alpine
      env:
        - name: POSTGRES_USER
          value: saleor
        - name: POSTGRES_PASSWORD
          value: saleor
        - name: POSTGRES_DB
          value: saleor
    - name: webapp
      image: magicsandbox/saleor:latest
      env:
        - name: DATABASE_URL
          value: postgres://saleor:saleor@localhost:5432/saleor
        - name: SECRET_KEY
          value: dummy
        - name: PORT
          value: "8000"
        - name: ALLOWED_HOSTS
          value: "*"
      lifecycle:
        postStart:
          exec:
            command: ["python", "manage.py", "migrate"]
      ports:
        - containerPort: 8000
