apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: cassandra
---
apiVersion: v1
kind: Pod
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  containers:
  - name: cassandra-container
    image: gcr.io/pso-examples/cassandra:3.11.4-v8
    env:
    - name: MAX_HEAP_SIZE
      value: 512M
    - name: HEAP_NEWSIZE
      value: 100M
    - name: CASSANDRA_SEEDS
      value: "cassandra.default"
    - name: CASSANDRA_CLUSTER_NAME
      value: "K8Demo"
    - name: CASSANDRA_DC
      value: "DC1-K8Demo"
    - name: CASSANDRA_RACK
      value: "Rack1-K8Demo"
