  apiVersion: v1
  kind: Pod
  metadata:
    name: downward-api
    labels:
      app: nginx-downward-api
      msb-label: awesome-value
    annotations:
      msb.com: awesome annotations!
  spec:
    containers:
    - image: nginx
      name: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: podinfo
    volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx-downward-api
