  apiVersion: v1
  kind: Pod
  metadata:
    name: empty-dir
    labels:
      app: nginx-empty-dir
  spec:
    containers:
    - image: nginx
      name: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
    volumes:
    - name: html
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx-empty-dir
