apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pg-to-s3-backuper
spec:
  schedule: "5 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backuper
            image: lgatica/pgdump-s3
            env:
            - name: POSTGRESQL_URI
              valueFrom:
                secretKeyRef:
                  name: backuper-cred
                  key: pg-uri
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backuper-cred
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backuper-cred
                  key: secret-key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backuper-cred
                  key: bucket
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
  