apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb
spec:
  version: 7.5.2
  count: 1
  elasticsearchRef:
    name: elastic
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 500m
