apiVersion: v1
kind: Service
metadata:
  name: kb-lb
spec:
  ports:
  - name: web
    port: 443
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kb
  type: LoadBalancer
