apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5tc2IuY29tIjp7InVzZXJuYW1lIjoibXNiIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJlbWFpbCI6InJlZ2lzdHJ5LXdvcmtzaG9wQG1zYi5jb20iLCJhdXRoIjoiYlhOaU9qRXlNelExTmc9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
